### ISSUE TITLE
Fix project directory structure

### ISSUE THREAD

**Issue by shoaibi** [AnatolyRugalev/yii-insertDelayedBehavior#1]
Could you change the dir structure of project so it has:
insert-delayed/InsertDelayedBehavior.php
README.md
instead of the protected hierarchy as not all of us use same hierarchy and it would be a pain to not be able to add this awesome behavior as git submodule.

**Comment by AnatolyRugalev** [comment]
What is default path to import?
EnsureNullBehavior uses

```
ext.yiiext.behaviors.model.ensureNull.EEnsureNullBehavior
```

Should I use ext.yiiext.behaviors.model path too?

**Comment by shoaibi** [comment]
aaaah, nope. Should i FFPR it? 

PS:
FFPR = Fork, fix, pull request

**Comment by AnatolyRugalev** [comment]
Yes, please
